### ISSUE TITLE
[Question] NuttX support?

### ISSUE THREAD

**Issue by fujitatomoya** [embedded-software-laboratory/embeddedRTPS#12]
We can see that it depends on lightweightIP (lwip) as network stack, but is there any plan to support NuttX as well?
NuttX uses mIP (micro IP) network stack instead of lwip, so that it will not be straight-forward to do that with current software stack.
we would like to bring the question if there is any plan or request for supporting NuttX.

Motivation is basically for more isolation as distributed system w/o agent(server/client architecture) with embedded micro-controllers.

**Comment by akampmann** [comment]
We currently dont have plans to support nuttX. Access to the networking API of lwIP is encapsulated in this class (7 methods): https://github.com/embedded-software-laboratory/embeddedRTPS/blob/master/src/communication/UdpDriver.cpp - So it should be fairly easy to write a UdpDriver for Nuttx. Implementing all 7 methods of the UdpDriver class should be all. 

There are a few calls to lwip/FreeRTOS OS API in the code base to create semaphores and mutex (ideally those will also be encapsulated in a separate class in the future). Some of my colleagues have ported embeddedRTPS to ChibiOS, replacing those few OS calls with NuttX specific calls shouldn't be a problem.

What target platform do you have in mind?

**Comment by vmayoral** [comment]
If available, I would definitely be interested in trying NuttX support as well. As for the target, running in the Cortex-R5 processors would be ideal.

**Comment by fujitatomoya** [comment]
> What target platform do you have in mind?

we have [Sony SPRESENSE](https://developer.sony.com/develop/spresense/) in our mind, but it will/can be NuttX generic. (https://nuttx.apache.org/docs/latest/introduction/supported_platforms.html)

**Comment by fujitatomoya** [comment]
i will go ahead to close this since community does not have any plan to support NuttX for now. thanks for sharing status and information. we would be back when we have anything comes up.
