### ISSUE TITLE
please add a license

### ISSUE THREAD

**Issue by takasehideki** [embedded-software-laboratory/embeddedRTPS#2]
This repository don't have a LICENSE.
Without a copyright license, nobody is legally allowed to use this code. Please choose a license. 

We plan to use the product you have achieved for our R&D activity.
If we may suggest it, the Apache 2.0 license is good choice because this permissive the license that also grant patent rights. And Apache 2.0 prevents you from being able to sue your users over patent infringement claims.

**Comment by akampmann** [comment]
embeddedRTPS is already released under MIT License: https://github.com/embedded-software-laboratory/embeddedRTPS/blob/master/LICENSE

We did not add a LICENSE file to the STM32 example repository. That repo includes embeddedRTPS as a submodule, and all the other files for the stm32 are generated using the code generator in STM32CubeIDE.

Does that answer your question?

**Comment by takasehideki** [comment]
@akampmann I'm really sorry I could not find LICENSE file. MIT is enough for us to utilize this repository into our activity. Thank you so much for developing this product.

**Comment by akampmann** [comment]
No problem! I'm curious to hear what you guys are doing with this, would you mind letting me know at some point?

**Comment by takasehideki** [comment]
@akampmann Our project is still WiP, but we'll let you know ASAP it will be published!!
