### ISSUE TITLE
Unable to receive data at subscriber using embedded RTPS with FreeRTOS used two ESP32 devices as Publisher & Subscriber

### ISSUE THREAD

**Issue by ManvithRaj** [embedded-software-laboratory/embeddedRTPS#24]
Hello @akampmann ,

I tried this Embedded RTPS  component with micro ros for both subscriber and publisher with two ESP32 Devices but problem is My publisher ESP32 publishing the data and My Subscriber ESP32 not receiving it but both are connected to same wifi-router.

Could you please help me here if I am missing anything or any configuration updated related to IP and Ports etc.

I am thinking that this communication will happen through by joining a IGMP Group with LWIP Where i could see that it is joining into group 239.255.0.1 based on udpdriver.c file prints but still there is no communication between them.

I have used same topic name for subscriber and publisher but still no luck.

Kindly please help in this. I am struggling with this issue from many days and also I am not less aware of  this LWIP and RTPS components.

Thank you in advance.

**Comment by akampmann** [comment]
Hi @ManvithRaj 

I do not maintain Micro-ROS on top of embeddedRTPS, sorry. I'm happy to look at a Wireshark recording to see if I spot anything.

Best regards
Alex

**Comment by ManvithRaj** [comment]
Closing this issue it is solved . Opening another new issue facing linking here
